### ISSUE TITLE
Document optimization levels for users

### ISSUE THREAD

**Issue by philpax** [rustformers/llm#219]
We mention that `llm` should be built as release, but users are likely going to want to know how to build the dependency as release while keeping their own code in debug.

```toml
[profile.dev.package.llm]
opt-level = 3
```

but for each affected crate. I wonder if there's a better way of doing that, or if we should make that call for our users directly.
